[package]
name = "rabbit-rs"
version = "0.1.2"
authors = ["stefanos.kouroupis <stefanos.kouroupis@cloudcall.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
lapin = "1.0.0"
futures-executor = "0.3.5"
futures = "0.3.5"
serde = "1.0.110"
serde_json = "1.0.53"