[package]
name = "rabbit-rs"
version = "0.1.0"
authors = ["stefanos.kouroupis <stefanos.kouroupis@cloudcall.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "0.39.7"
futures-executor = "0.3.5"